'$schema' = "https://awslabs.github.io/duvet/config/v0.4.0.json"

# List each source directory. A "**/*.go" pattern also scans .devbox.
[[source]]
pattern = "cmd/**/*.go"

[[source]]
pattern = "pkg/**/*.go"

[[source]]
pattern = "internal/**/*.go"

[[source]]
pattern = "sim/**/*.go"

[[source]]
pattern = "test/**/*.go"

[[specification]]
source = "spec/solas.md"

[report.html]
enabled = true

# The snapshot blocks any drop in requirement coverage.
[report.snapshot]
enabled = true
