//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated for solas. DO NOT EDIT.

// Code generated by openapi-gen. DO NOT EDIT.

package v1alpha1

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ClaimRef) OpenAPIModelName() string {
	return "dev.solas.v1alpha1.ClaimRef"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in Device) OpenAPIModelName() string {
	return "dev.solas.v1alpha1.Device"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in DeviceList) OpenAPIModelName() string {
	return "dev.solas.v1alpha1.DeviceList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in DeviceSpec) OpenAPIModelName() string {
	return "dev.solas.v1alpha1.DeviceSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in DeviceStatus) OpenAPIModelName() string {
	return "dev.solas.v1alpha1.DeviceStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in Member) OpenAPIModelName() string {
	return "dev.solas.v1alpha1.Member"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in MemberList) OpenAPIModelName() string {
	return "dev.solas.v1alpha1.MemberList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in MemberPolicy) OpenAPIModelName() string {
	return "dev.solas.v1alpha1.MemberPolicy"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in MemberPolicyList) OpenAPIModelName() string {
	return "dev.solas.v1alpha1.MemberPolicyList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in MemberPolicySpec) OpenAPIModelName() string {
	return "dev.solas.v1alpha1.MemberPolicySpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in MemberSpec) OpenAPIModelName() string {
	return "dev.solas.v1alpha1.MemberSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in MemberStatus) OpenAPIModelName() string {
	return "dev.solas.v1alpha1.MemberStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in MemberUsage) OpenAPIModelName() string {
	return "dev.solas.v1alpha1.MemberUsage"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in MemberUsageList) OpenAPIModelName() string {
	return "dev.solas.v1alpha1.MemberUsageList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in PreemptionRequest) OpenAPIModelName() string {
	return "dev.solas.v1alpha1.PreemptionRequest"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in Release) OpenAPIModelName() string {
	return "dev.solas.v1alpha1.Release"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in StoreFormat) OpenAPIModelName() string {
	return "dev.solas.v1alpha1.StoreFormat"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in StoreFormatList) OpenAPIModelName() string {
	return "dev.solas.v1alpha1.StoreFormatList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in UsageEntry) OpenAPIModelName() string {
	return "dev.solas.v1alpha1.UsageEntry"
}
