//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated for solas. DO NOT EDIT.

// Code generated by defaulter-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// RegisterDefaults adds defaulters functions to the given scheme.
// Public to allow building arbitrary schemes.
// All generated defaulters are covering - they call all nested defaulters.
func RegisterDefaults(scheme *runtime.Scheme) error {
	scheme.AddTypeDefaultingFunc(&Member{}, func(obj interface{}) { SetObjectDefaults_Member(obj.(*Member)) })
	scheme.AddTypeDefaultingFunc(&MemberList{}, func(obj interface{}) { SetObjectDefaults_MemberList(obj.(*MemberList)) })
	return nil
}

func SetObjectDefaults_Member(in *Member) {
	SetDefaults_MemberSpec(&in.Spec)
}

func SetObjectDefaults_MemberList(in *MemberList) {
	for i := range in.Items {
		a := &in.Items[i]
		SetObjectDefaults_Member(a)
	}
}
