//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated for solas. DO NOT EDIT.

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	solas "github.com/phoban01/solas/pkg/apis/solas"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*ClaimRef)(nil), (*solas.ClaimRef)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ClaimRef_To_solas_ClaimRef(a.(*ClaimRef), b.(*solas.ClaimRef), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*solas.ClaimRef)(nil), (*ClaimRef)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_solas_ClaimRef_To_v1alpha1_ClaimRef(a.(*solas.ClaimRef), b.(*ClaimRef), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Device)(nil), (*solas.Device)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Device_To_solas_Device(a.(*Device), b.(*solas.Device), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*solas.Device)(nil), (*Device)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_solas_Device_To_v1alpha1_Device(a.(*solas.Device), b.(*Device), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DeviceList)(nil), (*solas.DeviceList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_DeviceList_To_solas_DeviceList(a.(*DeviceList), b.(*solas.DeviceList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*solas.DeviceList)(nil), (*DeviceList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_solas_DeviceList_To_v1alpha1_DeviceList(a.(*solas.DeviceList), b.(*DeviceList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DeviceSpec)(nil), (*solas.DeviceSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_DeviceSpec_To_solas_DeviceSpec(a.(*DeviceSpec), b.(*solas.DeviceSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*solas.DeviceSpec)(nil), (*DeviceSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_solas_DeviceSpec_To_v1alpha1_DeviceSpec(a.(*solas.DeviceSpec), b.(*DeviceSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DeviceStatus)(nil), (*solas.DeviceStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_DeviceStatus_To_solas_DeviceStatus(a.(*DeviceStatus), b.(*solas.DeviceStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*solas.DeviceStatus)(nil), (*DeviceStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_solas_DeviceStatus_To_v1alpha1_DeviceStatus(a.(*solas.DeviceStatus), b.(*DeviceStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Member)(nil), (*solas.Member)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Member_To_solas_Member(a.(*Member), b.(*solas.Member), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*solas.Member)(nil), (*Member)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_solas_Member_To_v1alpha1_Member(a.(*solas.Member), b.(*Member), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MemberList)(nil), (*solas.MemberList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_MemberList_To_solas_MemberList(a.(*MemberList), b.(*solas.MemberList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*solas.MemberList)(nil), (*MemberList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_solas_MemberList_To_v1alpha1_MemberList(a.(*solas.MemberList), b.(*MemberList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MemberSpec)(nil), (*solas.MemberSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_MemberSpec_To_solas_MemberSpec(a.(*MemberSpec), b.(*solas.MemberSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*solas.MemberSpec)(nil), (*MemberSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_solas_MemberSpec_To_v1alpha1_MemberSpec(a.(*solas.MemberSpec), b.(*MemberSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MemberStatus)(nil), (*solas.MemberStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_MemberStatus_To_solas_MemberStatus(a.(*MemberStatus), b.(*solas.MemberStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*solas.MemberStatus)(nil), (*MemberStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_solas_MemberStatus_To_v1alpha1_MemberStatus(a.(*solas.MemberStatus), b.(*MemberStatus), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_ClaimRef_To_solas_ClaimRef(in *ClaimRef, out *solas.ClaimRef, s conversion.Scope) error {
	*out = *(*solas.ClaimRef)(unsafe.Pointer(in))
	return nil
}

// Convert_v1alpha1_ClaimRef_To_solas_ClaimRef is an autogenerated conversion function.
func Convert_v1alpha1_ClaimRef_To_solas_ClaimRef(in *ClaimRef, out *solas.ClaimRef, s conversion.Scope) error {
	return autoConvert_v1alpha1_ClaimRef_To_solas_ClaimRef(in, out, s)
}

func autoConvert_solas_ClaimRef_To_v1alpha1_ClaimRef(in *solas.ClaimRef, out *ClaimRef, s conversion.Scope) error {
	*out = *(*ClaimRef)(unsafe.Pointer(in))
	return nil
}

// Convert_solas_ClaimRef_To_v1alpha1_ClaimRef is an autogenerated conversion function.
func Convert_solas_ClaimRef_To_v1alpha1_ClaimRef(in *solas.ClaimRef, out *ClaimRef, s conversion.Scope) error {
	return autoConvert_solas_ClaimRef_To_v1alpha1_ClaimRef(in, out, s)
}

func autoConvert_v1alpha1_Device_To_solas_Device(in *Device, out *solas.Device, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_DeviceSpec_To_solas_DeviceSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_DeviceStatus_To_solas_DeviceStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_Device_To_solas_Device is an autogenerated conversion function.
func Convert_v1alpha1_Device_To_solas_Device(in *Device, out *solas.Device, s conversion.Scope) error {
	return autoConvert_v1alpha1_Device_To_solas_Device(in, out, s)
}

func autoConvert_solas_Device_To_v1alpha1_Device(in *solas.Device, out *Device, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_solas_DeviceSpec_To_v1alpha1_DeviceSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_solas_DeviceStatus_To_v1alpha1_DeviceStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_solas_Device_To_v1alpha1_Device is an autogenerated conversion function.
func Convert_solas_Device_To_v1alpha1_Device(in *solas.Device, out *Device, s conversion.Scope) error {
	return autoConvert_solas_Device_To_v1alpha1_Device(in, out, s)
}

func autoConvert_v1alpha1_DeviceList_To_solas_DeviceList(in *DeviceList, out *solas.DeviceList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]solas.Device)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_DeviceList_To_solas_DeviceList is an autogenerated conversion function.
func Convert_v1alpha1_DeviceList_To_solas_DeviceList(in *DeviceList, out *solas.DeviceList, s conversion.Scope) error {
	return autoConvert_v1alpha1_DeviceList_To_solas_DeviceList(in, out, s)
}

func autoConvert_solas_DeviceList_To_v1alpha1_DeviceList(in *solas.DeviceList, out *DeviceList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Device)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_solas_DeviceList_To_v1alpha1_DeviceList is an autogenerated conversion function.
func Convert_solas_DeviceList_To_v1alpha1_DeviceList(in *solas.DeviceList, out *DeviceList, s conversion.Scope) error {
	return autoConvert_solas_DeviceList_To_v1alpha1_DeviceList(in, out, s)
}

func autoConvert_v1alpha1_DeviceSpec_To_solas_DeviceSpec(in *DeviceSpec, out *solas.DeviceSpec, s conversion.Scope) error {
	*out = *(*solas.DeviceSpec)(unsafe.Pointer(in))
	return nil
}

// Convert_v1alpha1_DeviceSpec_To_solas_DeviceSpec is an autogenerated conversion function.
func Convert_v1alpha1_DeviceSpec_To_solas_DeviceSpec(in *DeviceSpec, out *solas.DeviceSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_DeviceSpec_To_solas_DeviceSpec(in, out, s)
}

func autoConvert_solas_DeviceSpec_To_v1alpha1_DeviceSpec(in *solas.DeviceSpec, out *DeviceSpec, s conversion.Scope) error {
	*out = *(*DeviceSpec)(unsafe.Pointer(in))
	return nil
}

// Convert_solas_DeviceSpec_To_v1alpha1_DeviceSpec is an autogenerated conversion function.
func Convert_solas_DeviceSpec_To_v1alpha1_DeviceSpec(in *solas.DeviceSpec, out *DeviceSpec, s conversion.Scope) error {
	return autoConvert_solas_DeviceSpec_To_v1alpha1_DeviceSpec(in, out, s)
}

func autoConvert_v1alpha1_DeviceStatus_To_solas_DeviceStatus(in *DeviceStatus, out *solas.DeviceStatus, s conversion.Scope) error {
	*out = *(*solas.DeviceStatus)(unsafe.Pointer(in))
	return nil
}

// Convert_v1alpha1_DeviceStatus_To_solas_DeviceStatus is an autogenerated conversion function.
func Convert_v1alpha1_DeviceStatus_To_solas_DeviceStatus(in *DeviceStatus, out *solas.DeviceStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_DeviceStatus_To_solas_DeviceStatus(in, out, s)
}

func autoConvert_solas_DeviceStatus_To_v1alpha1_DeviceStatus(in *solas.DeviceStatus, out *DeviceStatus, s conversion.Scope) error {
	*out = *(*DeviceStatus)(unsafe.Pointer(in))
	return nil
}

// Convert_solas_DeviceStatus_To_v1alpha1_DeviceStatus is an autogenerated conversion function.
func Convert_solas_DeviceStatus_To_v1alpha1_DeviceStatus(in *solas.DeviceStatus, out *DeviceStatus, s conversion.Scope) error {
	return autoConvert_solas_DeviceStatus_To_v1alpha1_DeviceStatus(in, out, s)
}

func autoConvert_v1alpha1_Member_To_solas_Member(in *Member, out *solas.Member, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_MemberSpec_To_solas_MemberSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_MemberStatus_To_solas_MemberStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_Member_To_solas_Member is an autogenerated conversion function.
func Convert_v1alpha1_Member_To_solas_Member(in *Member, out *solas.Member, s conversion.Scope) error {
	return autoConvert_v1alpha1_Member_To_solas_Member(in, out, s)
}

func autoConvert_solas_Member_To_v1alpha1_Member(in *solas.Member, out *Member, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_solas_MemberSpec_To_v1alpha1_MemberSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_solas_MemberStatus_To_v1alpha1_MemberStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_solas_Member_To_v1alpha1_Member is an autogenerated conversion function.
func Convert_solas_Member_To_v1alpha1_Member(in *solas.Member, out *Member, s conversion.Scope) error {
	return autoConvert_solas_Member_To_v1alpha1_Member(in, out, s)
}

func autoConvert_v1alpha1_MemberList_To_solas_MemberList(in *MemberList, out *solas.MemberList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]solas.Member)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_MemberList_To_solas_MemberList is an autogenerated conversion function.
func Convert_v1alpha1_MemberList_To_solas_MemberList(in *MemberList, out *solas.MemberList, s conversion.Scope) error {
	return autoConvert_v1alpha1_MemberList_To_solas_MemberList(in, out, s)
}

func autoConvert_solas_MemberList_To_v1alpha1_MemberList(in *solas.MemberList, out *MemberList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Member)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_solas_MemberList_To_v1alpha1_MemberList is an autogenerated conversion function.
func Convert_solas_MemberList_To_v1alpha1_MemberList(in *solas.MemberList, out *MemberList, s conversion.Scope) error {
	return autoConvert_solas_MemberList_To_v1alpha1_MemberList(in, out, s)
}

func autoConvert_v1alpha1_MemberSpec_To_solas_MemberSpec(in *MemberSpec, out *solas.MemberSpec, s conversion.Scope) error {
	*out = *(*solas.MemberSpec)(unsafe.Pointer(in))
	return nil
}

// Convert_v1alpha1_MemberSpec_To_solas_MemberSpec is an autogenerated conversion function.
func Convert_v1alpha1_MemberSpec_To_solas_MemberSpec(in *MemberSpec, out *solas.MemberSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_MemberSpec_To_solas_MemberSpec(in, out, s)
}

func autoConvert_solas_MemberSpec_To_v1alpha1_MemberSpec(in *solas.MemberSpec, out *MemberSpec, s conversion.Scope) error {
	*out = *(*MemberSpec)(unsafe.Pointer(in))
	return nil
}

// Convert_solas_MemberSpec_To_v1alpha1_MemberSpec is an autogenerated conversion function.
func Convert_solas_MemberSpec_To_v1alpha1_MemberSpec(in *solas.MemberSpec, out *MemberSpec, s conversion.Scope) error {
	return autoConvert_solas_MemberSpec_To_v1alpha1_MemberSpec(in, out, s)
}

func autoConvert_v1alpha1_MemberStatus_To_solas_MemberStatus(in *MemberStatus, out *solas.MemberStatus, s conversion.Scope) error {
	*out = *(*solas.MemberStatus)(unsafe.Pointer(in))
	return nil
}

// Convert_v1alpha1_MemberStatus_To_solas_MemberStatus is an autogenerated conversion function.
func Convert_v1alpha1_MemberStatus_To_solas_MemberStatus(in *MemberStatus, out *solas.MemberStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_MemberStatus_To_solas_MemberStatus(in, out, s)
}

func autoConvert_solas_MemberStatus_To_v1alpha1_MemberStatus(in *solas.MemberStatus, out *MemberStatus, s conversion.Scope) error {
	*out = *(*MemberStatus)(unsafe.Pointer(in))
	return nil
}

// Convert_solas_MemberStatus_To_v1alpha1_MemberStatus is an autogenerated conversion function.
func Convert_solas_MemberStatus_To_v1alpha1_MemberStatus(in *solas.MemberStatus, out *MemberStatus, s conversion.Scope) error {
	return autoConvert_solas_MemberStatus_To_v1alpha1_MemberStatus(in, out, s)
}
